[veux_pe]
title = "PixelExperience for Redmi Note 11 Pro 5G (veux)"
url = "https://download.pixelexperience.org/veux"
entrySelector = '[data-version="thirteen_plus"] .package__data .accordion_tab'
titleSelector = '.download__meta li:nth-child(2)'
linkSelector = ".device__support a:nth-child(1)"
contentSelector = ".changelogs__list"
dateSelector = ".date"
dateFormat = "yyyy/MM/dd"
